// Generated by CoffeeScript 1.7.1
angular.module('angular-flot', []).directive('flot', function() {
  return {
    restrict: 'EA',
    template: '<div></div>',
    scope: {
      dataset: '=',
      options: '='
    },
    link: function(scope, element, attributes) {
      var height, init, onDatasetChanged, onOptionsChanged, plotArea, width;
      width = attributes.width || '100%';
      height = attributes.height || '100%';
      if (!scope.dataset) {
        scope.dataset = [];
      }
      if (!scope.options) {
        scope.options = {
          legend: {
            show: false
          }
        };
      }
      plotArea = $(element.children()[0]);
      plotArea.css({
        width: width,
        height: height
      });
      init = function() {
        return $.plot(plotArea, scope.dataset, scope.options);
      };
      onDatasetChanged = function(dataset) {
        var plot;
        if (plot) {
          return plot.setData(dataset);
        } else {
          return plot = init();
        }
      };
      scope.$watch('dataset', onDatasetChanged, true);
      onOptionsChanged = function() {
        var plot;
        return plot = init();
      };
      return scope.$watch('options', onOptionsChanged, true);
    }
  };
});
